import Header from "./components/Header";
import Footer from "./components/Footer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' version='1.1' viewBox='0 0 16 16'%3E%3Cpath d='M2.67,0C1.19,0,0,1.19,0,2.67h0v10.67c0,1.47,1.19,2.67,2.67,2.67h10.67c1.47,0,2.67-1.19,2.67-2.67V2.67C16,1.19,14.81,0,13.33,0H2.67ZM13.66,12.97c.37-.25.75-.51,1.13-.77h.02c.07.11.15.22.22.33-.43.29-.87.59-1.3.88l-1.26.85c-.23-.66-.47-1.32-.7-1.97l-.52-1.45c-.49-1.35-1.23-2.03-2.62-2.38-.19.13-.37.25-.56.37v3.4c.54.19,1.04.43,1.52.75l.94-.79c.07.09.15.19.23.28-.71.6-1.42,1.2-2.13,1.8-1.43-.83-2.81-1.17-4.45-1.1-1.05.05-1.84.38-2.61,1.1-.08-.08-.15-.15-.23-.23.97-1.31,2.04-1.93,3.65-2.15.28-2.01-1.12-3.86-3.13-4.14-.01,0-.03,0-.04,0v-.33c.53-.22,1.04-.49,1.52-.81.56-.38,1.12-.77,1.68-1.15v-.83c0-1.53-1.83-2.31-2.93-1.25l-.27-.23c.74-.8,1.5-1.13,2.6-1.13,1.25,0,2.27,1.01,2.27,2.26,0,.01,0,.03,0,.04l3.37-2.3,2.83,3.63c-.9.59-1.8,1.19-2.69,1.78,1.27.68,2.02,1.54,2.51,2.9l.95,2.66ZM3.21,7.16c.75.33,1.32.78,1.81,1.43v-2.67l-.88.61c-.31.21-.62.42-.93.63M6.69,11.9c.34.05.67.12,1,.21V4.11l-1,.68v7.11ZM8.05,3.85v4.54l3.24-2.15-2.35-3.01-.89.61Z'/%3E%3C/svg%3E",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
